server:
  port: 8000
  link: http://localhost:8000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gxtj?useUnicode=true&characterEncoding=utf8
    ip: localhost
    port: 3306
    database: gxtj
    driverLocation: sql/mysql-connector-java-5.1.30.jar

  thymeleaf:
    cache: false
    check-template: false

  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.qq.com                 #邮件服务器
    username: 3098524317@qq.com       #用户名
    password: rpjawgzntzicdfha        #授权码
    default-encoding: utf-8           #编码类型
    port: 587                         #端口

  redis:                              #配置redis数据库连接
    host: 127.0.0.1
    port: 63791
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    database: 0                       #默认是索引为0的数据库
    password:
    timeout: 0
    sentinel:
      master: mymaster                #哨兵模式
      nodes: 127.0.0.1:26279,127.0.0.1:63794,127.0.0.1:26379

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: gxtj


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhoulin.demo.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true               #二级缓存的全局开关

com:
  liangliang:
    custom:
      windows-path: d:/gxtj/
      linux-path: /gxtj
      images-path: file:d:/gxtj/     #访问外部静态文件的路径

jwt:
  secret: zhoulinSecret             #加密
  header: token
  validity-time: 43200000              #token有效时间

mail:
  fromMail:
    addr: 3098524317@qq.com         #邮件发送人
